In [3]:
import pandas as pd
import numpy as np

In [4]:
# Read the books dataset and explore it.

In [5]:
book_df=pd.read_csv('BX-Books.csv',encoding='latin-1')

/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [6]:
book_df.head()

isbn                                         book_title  \
0  195153448                                Classical Mythology   
1    2005018                                       Clara Callan   
2   60973129                               Decision in Normandy   
3  374157065  Flu: The Story of the Great Influenza Pandemic...   
4  393045218                             The Mummies of Urumchi   

            book_author year_of_publication                   publisher  
0    Mark P. O. Morford                2002     Oxford University Press  
1  Richard Bruce Wright                2001       HarperFlamingo Canada  
2          Carlo D'Este                1991             HarperPerennial  
3      Gina Bari Kolata                1999        Farrar Straus Giroux  
4       E. J. W. Barber                1999  W. W. Norton &amp; Company

In [7]:
book_df.shape

(271379, 5)

In [8]:
book_df.describe()

isbn      book_title      book_author year_of_publication  \
count       271379          271379           271378              271379   
unique      271379          242150           102042                 202   
top     3150058996  Selected Poems  Agatha Christie                2002   
freq             1              27              632               17145   

        publisher  
count      271377  
unique      16823  
top     Harlequin  
freq         7535

In [9]:
# Clean up NaN values.

In [10]:
book_df.isna().any()

isbn                   False
book_title             False
book_author             True
year_of_publication    False
publisher               True
dtype: bool

In [11]:
book_df.fillna('Others')

isbn                                         book_title  \
0        195153448                                Classical Mythology   
1          2005018                                       Clara Callan   
2         60973129                               Decision in Normandy   
3        374157065  Flu: The Story of the Great Influenza Pandemic...   
4        393045218                             The Mummies of Urumchi   
...            ...                                                ...   
271374   440400988                         There's a Bat in Bunk Five   
271375   525447644                            From One to One Hundred   
271376  006008667X  Lily Dale : The True Story of the Town that Ta...   
271377   192126040                        Republic (World's Classics)   
271378   767409752  A Guided Tour of Rene Descartes' Meditations o...   

                 book_author year_of_publication  \
0         Mark P. O. Morford                2002   
1       Richard Bruce Wright                2001   
2               Carlo D'Este                1991   
3           Gina Bari Kolata                1999   
4            E. J. W. Barber                1999   
...                      ...                 ...   
271374        Paula Danziger                1988   
271375            Teri Sloat                1991   
271376      Christine Wicker                2004   
271377                 Plato                1996   
271378   Christopher  Biffle                2000   

                                               publisher  
0                                Oxford University Press  
1                                  HarperFlamingo Canada  
2                                        HarperPerennial  
3                                   Farrar Straus Giroux  
4                             W. W. Norton &amp; Company  
...                                                  ...  
271374                   Random House Childrens Pub (Mm)  
271375                                      Dutton Books  
271376                                HarperSanFrancisco  
271377                           Oxford University Press  
271378  McGraw-Hill Humanities/Social Sciences/Languages  

[271379 rows x 5 columns]

In [12]:
rating_df=pd.read_csv('BX-Book-Ratings.csv',encoding='latin-1',nrows=10000)

In [13]:
rating_df.head()

user_id        isbn  rating
0   276725  034545104X       0
1   276726   155061224       5
2   276727   446520802       0
3   276729  052165615X       3
4   276729   521795028       6

In [14]:
rating_df.isna().any()

user_id    False
isbn       False
rating     False
dtype: bool

In [15]:
user_df=pd.read_csv('BX-Users.csv',encoding='latin-1')

/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [16]:
user_df.head()

user_id                            Location   Age
0       1                  nyc, new york, usa   NaN
1       2           stockton, california, usa  18.0
2       3     moscow, yukon territory, russia   NaN
3       4           porto, v.n.gaia, portugal  17.0
4       5  farnborough, hants, united kingdom   NaN

In [17]:
user_df.fillna(0)

user_id                            Location   Age
0            1                  nyc, new york, usa   0.0
1            2           stockton, california, usa  18.0
2            3     moscow, yukon territory, russia   0.0
3            4           porto, v.n.gaia, portugal  17.0
4            5  farnborough, hants, united kingdom   0.0
...        ...                                 ...   ...
278854  278854               portland, oregon, usa   0.0
278855  278855  tacoma, washington, united kingdom  50.0
278856  278856           brampton, ontario, canada   0.0
278857  278857           knoxville, tennessee, usa   0.0
278858  278858                dublin, n/a, ireland   0.0

[278859 rows x 3 columns]

In [18]:
# Merging book and rating on isbn
rating_df=pd.merge(rating_df,book_df,on='isbn')

In [19]:
rating_df

user_id        isbn  rating                book_title  \
0      276725  034545104X       0      Flesh Tones: A Novel   
1      276726   155061224       5          Rites of Passage   
2      276727   446520802       0              The Notebook   
3      278418   446520802       0              The Notebook   
4      276729  052165615X       3            Help!: Level 1   
...       ...         ...     ...                       ...   
8696      243   385720106       7        A Map of the World   
8697      243   425092917       0    The Accidental Tourist   
8698      243   425098834       0     If Morning Ever Comes   
8699      243   425163407       9        Unnatural Exposure   
8700      243   425164403       0  Only Love (Magical Love)   

                    book_author year_of_publication  \
0                    M. J. Rose                2002   
1                    Judith Rae                2001   
2               Nicholas Sparks                1996   
3               Nicholas Sparks                1996   
4                 Philip Prowse                1999   
...                         ...                 ...   
8696              Jane Hamilton                1999   
8697                 Anne Tyler                1994   
8698                 Anne Tyler                1983   
8699  Patricia Daniels Cornwell                1998   
8700                Erich Segal                1998   

                       publisher  
0               Ballantine Books  
1                         Heinle  
2                   Warner Books  
3                   Warner Books  
4     Cambridge University Press  
...                          ...  
8696      Anchor Books/Doubleday  
8697    Berkley Publishing Group  
8698    Berkley Publishing Group  
8699    Berkley Publishing Group  
8700    Berkley Publishing Group  

[8701 rows x 7 columns]

In [20]:
# The number of unique users and books
n_users=rating_df.user_id.nunique()
n_books=rating_df.isbn.nunique()

In [21]:
print('Number of Users: '+ str(n_users))

Number of Users: 828


In [22]:
print('Number of Books: '+ str(n_books))

Number of Books: 8051


In [23]:
# Convert ISBN to numeric numbers in the correct order. 
isbn_list = rating_df.isbn.unique()
print(" Length of isbn List:", len(isbn_list))
def isbn_numeric(isbn):
    itemindex = np.where(isbn_list==isbn)
    return itemindex[0][0]

 Length of isbn List: 8051


In [24]:
#Convert user_id to numeric numbers in the correct order. 
userid_list = rating_df.user_id.unique()
print(" Length of userid List:", len(userid_list))
def userid_numeric(user_id):
    itemindex = np.where(userid_list==user_id)
    return itemindex[0][0]

 Length of userid List: 828


In [25]:
# Convert user_id to the ordered list i.e. from 0...n-1
rating_df['userid_order'] =rating_df['user_id'].apply(userid_numeric)

In [26]:
# Convert ISBN to the ordered list i.e. from 0...n-1

In [27]:
rating_df['isbn_order'] = rating_df['isbn'].apply(isbn_numeric)

In [28]:
#Re-index columns to build matrix later on.

In [29]:
new_column=['userid_order', 'isbn_order', 'rating', 'book_title', 'book_author','year_of_publication','publisher']
rating_df =rating_df.reindex(columns= new_column)
rating_df.head()

userid_order  isbn_order  rating            book_title      book_author  \
0             0           0       0  Flesh Tones: A Novel       M. J. Rose   
1             1           1       5      Rites of Passage       Judith Rae   
2             2           2       0          The Notebook  Nicholas Sparks   
3             3           2       0          The Notebook  Nicholas Sparks   
4             4           3       3        Help!: Level 1    Philip Prowse   

  year_of_publication                   publisher  
0                2002            Ballantine Books  
1                2001                      Heinle  
2                1996                Warner Books  
3                1996                Warner Books  
4                1999  Cambridge University Press

In [30]:
# Split data into two sets (training and testing)

In [31]:
from sklearn.model_selection import train_test_split
train_data,test_data=train_test_split(rating_df,test_size=0.25)

In [32]:
train_data_matrix=np.zeros((n_users,n_books))

In [33]:
for line in train_data.itertuples():
    train_data_matrix[line[1]-1,line[2]-1]=line[3]

In [34]:
test_data_matrix=np.zeros((n_users,n_books))

In [35]:
for line in test_data.itertuples():
    test_data_matrix[line[1]-1,line[2]-1]=line[3]

In [36]:
# Calculate the cosine similarity

In [37]:
from sklearn.metrics import pairwise_distances
user_similarity=pairwise_distances(train_data_matrix,metric='cosine')
book_similarity=pairwise_distances(train_data_matrix.T,metric='cosine')

In [38]:
user_similarity

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

In [39]:
user_similarity.shape

(828, 828)

In [40]:
book_similarity

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

In [41]:
book_similarity.shape

(8051, 8051)

In [42]:
# Use the evaluation metrics to make predictions.

In [43]:
# Predictions using user-based collaborative filtering

In [44]:
mean_user_rating = train_data_matrix.mean(axis=1)[:, np.newaxis] 
ratings_diff = (train_data_matrix - mean_user_rating) 
user_pred = mean_user_rating + user_similarity.dot(ratings_diff) / np.array([np.abs(user_similarity).sum(axis=1)]).T

In [45]:
print(user_pred.shape)
print('User based prediction:',user_pred)

(828, 8051)
User based prediction: [[-0.00184991 -0.00184991 -0.00184991 ... -0.00184991 -0.00184991
  -0.00184991]
 [-0.00184991 -0.00184991 -0.00184991 ... -0.00184991 -0.00184991
  -0.00184991]
 [ 0.05411142  0.05411142  0.05411142 ...  0.05411142  0.05411142
   0.05411142]
 ...
 [-0.00184991 -0.00184991 -0.00184991 ... -0.00184991 -0.00184991
  -0.00184991]
 [-0.00184991 -0.00184991 -0.00184991 ... -0.00184991 -0.00184991
  -0.00184991]
 [-0.00184991 -0.00184991 -0.00184991 ... -0.00184991 -0.00184991
  -0.00184991]]


In [46]:
# Predictions using item-based collaborative filtering

In [47]:
book_pred = train_data_matrix.dot(book_similarity) / np.array([np.abs(book_similarity).sum(axis=1)])

In [48]:
print('Item based prediction:',book_pred)
print(book_pred.shape)

Item based prediction: [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.05590062 0.05590062 0.05590062 ... 0.05590062 0.05590062 0.05590062]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
(828, 8051)


In [49]:
# Use RMSE to evaluate the predictions

In [50]:
from sklearn.metrics import mean_squared_error
user_prediction= user_pred[test_data_matrix.nonzero()].flatten() 
ground_truth = test_data_matrix[test_data_matrix.nonzero()].flatten()
user_rmse=np.sqrt(mean_squared_error(user_prediction, ground_truth))

In [51]:
book_prediction= book_pred[test_data_matrix.nonzero()].flatten() 
ground_truth = test_data_matrix[test_data_matrix.nonzero()].flatten()
book_rmse=np.sqrt(mean_squared_error(book_prediction, ground_truth))

In [52]:
print('User-based collaborative filtering RMSE: ' + str(user_rmse))
print('Item-based collaborative filtering RMSE: ' + str(book_rmse))

User-based collaborative filtering RMSE: 7.646618831875677
Item-based collaborative filtering RMSE: 7.646152363953664
